[IG]
ig = fsh-generated/resources/ImplementationGuide-nmdp.fhir.ig-builder.json
template = fhir.base.template#current
usage-stats-opt-out = true
; Pin the publisher version for reproducible builds
; publisher = 1.6.28
