id: example.fhir.my-ig
canonical: http://example.org/ig/my-ig
name: MyFHIRIG
title: My FHIR Implementation Guide
description: >-
  A template Implementation Guide for authoring FHIR profiles
  using FHIR Shorthand. Replace this description with your own.
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build
license: Apache-2.0
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
publisher:
  name: Your Organization
  url: https://example.org
  email: fhir@example.org

dependencies:
  hl7.fhir.us.core: 6.1.0

pages:
  index.md:
    title: Home
  conventions.md:
    title: Conventions
  identifiers.md:
    title: Identifiers

menu:
  Home: index.html
  Conventions: conventions.html
  Identifiers: identifiers.html
  Artifacts: artifacts.html

parameters:
  show-hierarchies: true
  excludettl: true
